import { afterEach, describe, expect, it, vi } from "vitest";
import { getAiProviderConfigurations, selectAiProvider } from "../model-routing-policy";
import { routeAiRequest } from "../router/aiRouter";
import { createGroqProvider, groqModelChain } from "./groqProvider";
import type { AiProviderConfig } from "../types";

const groqConfig = () => getAiProviderConfigurations({ GROQ_API_KEY: "test-key" } as unknown as NodeJS.ProcessEnv)
  .find((provider) => provider.name === "groq") as AiProviderConfig;

const request = {
  prompt: "Summarize the referral backlog trend.",
  task: "general_chat" as const,
  context: { organizationId: "org-nehm", userId: "user-director", userRole: "Executive" },
};

const classification = {
  category: "general_chat",
  sensitivity: "internal",
  language: "english",
  requiredReasoning: "low",
  humanReviewRequired: false,
} as never;

function reply(status: number, body: unknown = {}) {
  return new Response(JSON.stringify(body), { status });
}

describe("Groq free-tier provider", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
  });

  it("is the default route when GROQ_API_KEY is set, with no billed cost", async () => {
    const fetchMock = vi.fn(async () => reply(200, {
      choices: [{ message: { content: "Backlog down 12% this week." } }],
      usage: { prompt_tokens: 1000, completion_tokens: 500 },
    }));
    vi.stubGlobal("fetch", fetchMock);

    const result = await routeAiRequest(request, { GROQ_API_KEY: "test-key", AXXESS_AI_ROUTING_MODE: "demo" } as unknown as NodeJS.ProcessEnv);

    expect(result.providerUsed).toBe("groq");
    expect(result.answer).toBe("Backlog down 12% this week.");
    expect(fetchMock).toHaveBeenCalledTimes(1);
    const [url, init] = fetchMock.mock.calls[0] as unknown as [string, RequestInit];
    expect(url).toBe("https://api.groq.com/openai/v1/chat/completions");
    expect(JSON.parse(String(init.body)).model).toBe("openai/gpt-oss-120b");
    expect(result.estimatedCostUsd).toBe(0);
  });

  it("keeps paid providers off by default even when their keys are present", async () => {
    const fetchMock = vi.fn();
    vi.stubGlobal("fetch", fetchMock);
    const env = { OPENAI_API_KEY: "k", OPENROUTER_API_KEY: "k", ANTHROPIC_API_KEY: "k", AXXESS_AI_ROUTING_MODE: "demo" } as unknown as NodeJS.ProcessEnv;

    const providers = getAiProviderConfigurations(env);
    expect(providers.find((p) => p.name === "openai")).toMatchObject({ configured: false, status: "disabled" });
    expect(providers.find((p) => p.name === "deepseek")).toMatchObject({ configured: false, status: "disabled" });

    const result = await routeAiRequest(request, env);
    expect(result.providerUsed).toBe("local");
    expect(fetchMock).not.toHaveBeenCalled();
  });

  it("puts Groq ahead of paid providers even when paid providers are enabled", () => {
    const providers = getAiProviderConfigurations({ GROQ_API_KEY: "k", OPENAI_API_KEY: "k", AXXESS_AI_PAID_PROVIDERS: "enabled" } as unknown as NodeJS.ProcessEnv);
    const { provider } = selectAiProvider(classification, request.context, providers);
    expect(provider.name).toBe("groq");
  });

  it("falls back to the second free model on a 429 from the first", async () => {
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(reply(429, { error: { message: "rate limit" } }))
      .mockResolvedValueOnce(reply(200, { choices: [{ message: { content: "from 20b" } }] }));
    const result = await createGroqProvider(groqConfig(), { GROQ_API_KEY: "k" } as unknown as NodeJS.ProcessEnv, fetchMock).complete(request, classification);

    expect(result.text).toBe("from 20b");
    expect(result.confidence).toBeGreaterThanOrEqual(0.62);
    const models = fetchMock.mock.calls.map((call) => JSON.parse(String((call[1] as RequestInit).body)).model);
    expect(models).toEqual(["openai/gpt-oss-120b", "openai/gpt-oss-20b"]);
  });

  it("does not retry a non-retryable error such as 401, and reports it as unverified", async () => {
    const fetchMock = vi.fn().mockResolvedValue(reply(401));
    const result = await createGroqProvider(groqConfig(), { GROQ_API_KEY: "k" } as unknown as NodeJS.ProcessEnv, fetchMock).complete(request, classification);

    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(result.confidence).toBeLessThan(0.62);
    expect(result.text).toContain("not generated by a live model call");
  });

  it("parses tool calls, including malformed arguments, without throwing", async () => {
    const fetchMock = vi.fn().mockResolvedValue(reply(200, { choices: [{ message: { content: null, tool_calls: [
      { id: "c1", function: { name: "list_tasks", arguments: "{\"status\":\"open\"}" } },
      { id: "c2", function: { name: "create_task", arguments: "{not json" } },
    ] } }] }));
    const result = await createGroqProvider(groqConfig(), { GROQ_API_KEY: "k" } as unknown as NodeJS.ProcessEnv, fetchMock).complete(request, classification);

    expect(result.toolCalls?.[0]).toEqual({ id: "c1", name: "list_tasks", arguments: { status: "open" } });
    expect(result.toolCalls?.[1].arguments).toHaveProperty("__parseError");
  });

  it("makes no call without a key", async () => {
    const fetchMock = vi.fn();
    const result = await createGroqProvider(groqConfig(), {} as NodeJS.ProcessEnv, fetchMock).complete(request, classification);
    expect(fetchMock).not.toHaveBeenCalled();
    expect(result.confidence).toBeLessThan(0.62);
  });

  it("honours model overrides and an empty fallback", () => {
    expect(groqModelChain({ GROQ_MODEL_ID: "qwen/qwen3.8-27b", GROQ_FALLBACK_MODEL_ID: "" } as unknown as NodeJS.ProcessEnv)).toEqual(["qwen/qwen3.8-27b"]);
    expect(groqModelChain({} as NodeJS.ProcessEnv)).toEqual(["openai/gpt-oss-120b", "openai/gpt-oss-20b"]);
  });
});
