import type { AiProviderAdapter, AiProviderConfig, AiProviderCompletion, AiPromptRequest, AiToolCall } from "../types";

// Free models (founder decision 2026-10-05): Groq's free tier, no card. Model ids confirmed
// against Groq's live /openai/v1/models listing on 2026-10-05, not assumed. gpt-oss-120b first,
// gpt-oss-20b as a free fallback -- Groq rate-limits each model separately, so a 429 on one
// model is usually not a 429 on the other.
const GROQ_ENDPOINT = "https://api.groq.com/openai/v1/chat/completions";
export const GROQ_DEFAULT_MODEL = "openai/gpt-oss-120b";
export const GROQ_DEFAULT_FALLBACK_MODEL = "openai/gpt-oss-20b";
// The free tier allows 8,000 tokens per minute per model (Groq's x-ratelimit-limit-tokens
// header, 2026-10-05). A large max_tokens reservation leaves no room for a second call in the
// same minute, so the default stays well under it.
const GROQ_DEFAULT_MAX_TOKENS = 2000;

type GroqToolCall = {
  id?: string;
  function?: { name?: string; arguments?: string };
};

type GroqChatResponse = {
  choices?: Array<{ message?: { content?: string | null; tool_calls?: GroqToolCall[] } }>;
  usage?: { prompt_tokens?: number; completion_tokens?: number };
};

// Same defensive parse as openAiProvider.ts -- Groq's chat completions API is OpenAI-compatible,
// so the shape (and the malformed-JSON risk) is identical.
function parseGroqToolCalls(raw: GroqToolCall[] | undefined): AiToolCall[] {
  if (!raw?.length) return [];
  return raw
    .filter((call): call is GroqToolCall & { id: string; function: { name: string } } =>
      Boolean(call.id && call.function?.name))
    .map((call) => {
      let args: Record<string, unknown> = {};
      try {
        args = call.function.arguments ? JSON.parse(call.function.arguments) : {};
      } catch {
        args = { __parseError: "Groq returned malformed JSON arguments for this tool call.", __raw: call.function.arguments };
      }
      return { id: call.id, name: call.function.name, arguments: args };
    });
}

export function groqModelChain(env: NodeJS.ProcessEnv = process.env): string[] {
  const primary = env.GROQ_MODEL_ID || GROQ_DEFAULT_MODEL;
  // An explicitly empty GROQ_FALLBACK_MODEL_ID disables the fallback.
  const fallback = env.GROQ_FALLBACK_MODEL_ID ?? GROQ_DEFAULT_FALLBACK_MODEL;
  return [...new Set([primary, fallback].filter(Boolean))];
}

function requestBody(model: string, request: AiPromptRequest, env: NodeJS.ProcessEnv) {
  return {
    model,
    max_tokens: Number(env.GROQ_MAX_TOKENS) || GROQ_DEFAULT_MAX_TOKENS,
    temperature: 0.2,
    messages: [
      { role: "user", content: request.prompt },
      ...(request.priorMessages ?? []).map((message) =>
        message.role === "assistant"
          ? { role: "assistant", content: message.content, tool_calls: message.toolCalls?.map((call) => ({
              id: call.id,
              type: "function",
              function: { name: call.name, arguments: JSON.stringify(call.arguments) },
            })) }
          : { role: "tool", tool_call_id: message.toolCallId, content: message.content },
      ),
    ],
    ...(request.tools?.length ? {
      tools: request.tools.map((tool) => ({
        type: "function",
        function: { name: tool.name, description: tool.description, parameters: tool.parameters },
      })),
      tool_choice: "auto",
    } : {}),
  };
}

// Worth trying the next model: rate limits and Groq-side failures. A 400/401 would fail the same
// way on every model, so those stop the chain.
function retryable(status: number) {
  return status === 429 || status >= 500;
}

export function createGroqProvider(
  config: AiProviderConfig,
  env: NodeJS.ProcessEnv = process.env,
  fetchImpl: typeof fetch = fetch,
): AiProviderAdapter {
  return {
    config,
    async complete(request): Promise<AiProviderCompletion> {
      const startedAt = Date.now();
      const apiKey = env.GROQ_API_KEY;
      const unverified = (reason: string): AiProviderCompletion => ({
        text: `${config.displayName} ${reason}. This response was not generated by a live model call; treat it as unverified.`,
        confidence: 0.3,
        latencyMs: Date.now() - startedAt,
      });

      if (!apiKey) {
        return {
          text: `${config.displayName} is not fully configured (missing Groq API key). No live model call was made.`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }

      let lastFailure = "request failed";
      for (const model of groqModelChain(env)) {
        try {
          const response = await fetchImpl(GROQ_ENDPOINT, {
            method: "POST",
            headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
            body: JSON.stringify(requestBody(model, request, env)),
          });

          if (!response.ok) {
            lastFailure = `request failed (${response.status} on ${model})`;
            if (retryable(response.status)) continue;
            return unverified(lastFailure);
          }

          const payload = await response.json() as GroqChatResponse;
          const text = payload.choices?.[0]?.message?.content;
          const toolCalls = parseGroqToolCalls(payload.choices?.[0]?.message?.tool_calls);
          if (!text && toolCalls.length === 0) {
            lastFailure = `returned no content (${model})`;
            continue;
          }

          return {
            text: text ?? "",
            confidence: 0.78,
            latencyMs: Date.now() - startedAt,
            usage: { promptTokens: payload.usage?.prompt_tokens ?? 0, completionTokens: payload.usage?.completion_tokens ?? 0 },
            // Free tier: no billed cost to record against a spend guard.
            actualCostUsd: 0,
            ...(toolCalls.length ? { toolCalls } : {}),
          };
        } catch (error) {
          lastFailure = `request failed (${error instanceof Error ? error.message : "Unknown error"})`;
        }
      }
      return unverified(lastFailure);
    },
  };
}
