import type { AiProviderAdapter, AiProviderConfig } from "../types";
import { checkProviderBudgetHeadroom, recordProviderSpend } from "../aiSpendGuard";

// Model slugs and per-token pricing verified directly against openrouter.ai's own model pages
// (2026-07-27) -- not guessed. Pricing is a point-in-time snapshot; OpenRouter pricing changes,
// so this is read as "best known at implementation time," matching this program's own evidence
// discipline (see GLOBAL_GTM_AI_ROUTER_ROADMAP_2026_07_27.md Non-Negotiables).
const OPENROUTER_MODEL_SLUG: Partial<Record<AiProviderConfig["name"], string>> = {
  kimi: "moonshotai/kimi-k2",
  deepseek: "deepseek/deepseek-chat",
};

const OPENROUTER_PRICING_PER_TOKEN: Partial<Record<AiProviderConfig["name"], { prompt: number; completion: number }>> = {
  kimi: { prompt: 0.00000057, completion: 0.0000023 },
  deepseek: { prompt: 0.0000002002, completion: 0.0000008001 },
};

const OPENROUTER_ENDPOINT = "https://openrouter.ai/api/v1/chat/completions";

// Kimi and DeepSeek share one OpenRouter account/credit pool -- the spend guard tracks and checks
// against that shared balance, not per-model, matching how OpenRouter itself bills.
const OPENROUTER_BUDGET_PROVIDER = "openrouter";

type OpenRouterChatResponse = {
  choices?: Array<{ message?: { content?: string } }>;
  usage?: { prompt_tokens?: number; completion_tokens?: number };
};

export function createOpenRouterProvider(
  config: AiProviderConfig,
  env: NodeJS.ProcessEnv = process.env,
): AiProviderAdapter {
  const modelSlug = OPENROUTER_MODEL_SLUG[config.name];
  const pricing = OPENROUTER_PRICING_PER_TOKEN[config.name];

  return {
    config,
    async complete(request) {
      const startedAt = Date.now();
      const apiKey = env.OPENROUTER_API_KEY;

      if (!apiKey || !modelSlug) {
        return {
          text: `${config.displayName} is not fully configured (missing OpenRouter API key or model mapping). No live model call was made.`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }

      const budget = await checkProviderBudgetHeadroom(OPENROUTER_BUDGET_PROVIDER);
      if (!budget.ok) {
        return {
          text: `${config.displayName} call skipped: ${budget.reason}`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }

      try {
        const response = await fetch(OPENROUTER_ENDPOINT, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${apiKey}`,
            "Content-Type": "application/json",
            "HTTP-Referer": env.NEXT_PUBLIC_APP_URL ?? "https://landing.triaxisventures.com",
            "X-Title": "AXXESS TRIaxis",
          },
          body: JSON.stringify({
            model: modelSlug,
            messages: [{ role: "user", content: request.prompt }],
          }),
        });

        if (!response.ok) {
          return {
            text: `${config.displayName} request failed (${response.status}). This response was not generated by a live model call; treat it as unverified.`,
            confidence: 0.3,
            latencyMs: Date.now() - startedAt,
          };
        }

        const payload = await response.json() as OpenRouterChatResponse;
        const text = payload.choices?.[0]?.message?.content;
        const promptTokens = payload.usage?.prompt_tokens ?? 0;
        const completionTokens = payload.usage?.completion_tokens ?? 0;
        const actualCostUsd = pricing
          ? Number((promptTokens * pricing.prompt + completionTokens * pricing.completion).toFixed(6))
          : undefined;

        if (!text) {
          return {
            text: `${config.displayName} returned no content. This response was not generated by a live model call; treat it as unverified.`,
            confidence: 0.3,
            latencyMs: Date.now() - startedAt,
          };
        }

        if (actualCostUsd) {
          await recordProviderSpend(OPENROUTER_BUDGET_PROVIDER, actualCostUsd);
        }

        return {
          text,
          confidence: 0.78,
          latencyMs: Date.now() - startedAt,
          usage: { promptTokens, completionTokens },
          actualCostUsd,
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return {
          text: `${config.displayName} request failed (${message}). This response was not generated by a live model call; treat it as unverified.`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }
    },
  };
}
