import type { AiProviderAdapter, AiProviderConfig } from "../types";
import { checkProviderBudgetHeadroom, recordProviderSpend } from "../aiSpendGuard";

const OPENAI_ENDPOINT = "https://api.openai.com/v1/chat/completions";
const OPENAI_MODEL = "gpt-4o-mini";
const OPENAI_BUDGET_PROVIDER = "openai";

// Pricing verified against OpenAI's own published pricing at implementation time (2026-07-31),
// same "best known when written, may drift" honesty convention as openRouterProvider.ts.
const OPENAI_PRICING_PER_TOKEN = { prompt: 0.00000015, completion: 0.0000006 };

type OpenAiChatResponse = {
  choices?: Array<{ message?: { content?: string } }>;
  usage?: { prompt_tokens?: number; completion_tokens?: number };
};

export function createOpenAiProvider(
  config: AiProviderConfig,
  env: NodeJS.ProcessEnv = process.env,
): AiProviderAdapter {
  return {
    config,
    async complete(request) {
      const startedAt = Date.now();
      const apiKey = env.OPENAI_API_KEY;

      if (!apiKey) {
        return {
          text: `${config.displayName} is not fully configured (missing OpenAI API key). No live model call was made.`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }

      // Fail closed: real, billed calls to the founder's own OpenAI account only proceed once the
      // spend guard confirms real headroom below the account's safety margin. See aiSpendGuard.ts.
      const budget = await checkProviderBudgetHeadroom(OPENAI_BUDGET_PROVIDER);
      if (!budget.ok) {
        return {
          text: `${config.displayName} call skipped: ${budget.reason}`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }

      try {
        const response = await fetch(OPENAI_ENDPOINT, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${apiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model: OPENAI_MODEL,
            messages: [{ role: "user", content: request.prompt }],
          }),
        });

        if (!response.ok) {
          return {
            text: `${config.displayName} request failed (${response.status}). This response was not generated by a live model call; treat it as unverified.`,
            confidence: 0.3,
            latencyMs: Date.now() - startedAt,
          };
        }

        const payload = await response.json() as OpenAiChatResponse;
        const text = payload.choices?.[0]?.message?.content;
        const promptTokens = payload.usage?.prompt_tokens ?? 0;
        const completionTokens = payload.usage?.completion_tokens ?? 0;
        const actualCostUsd = Number((promptTokens * OPENAI_PRICING_PER_TOKEN.prompt + completionTokens * OPENAI_PRICING_PER_TOKEN.completion).toFixed(6));

        if (!text) {
          return {
            text: `${config.displayName} returned no content. This response was not generated by a live model call; treat it as unverified.`,
            confidence: 0.3,
            latencyMs: Date.now() - startedAt,
          };
        }

        if (actualCostUsd > 0) {
          await recordProviderSpend(OPENAI_BUDGET_PROVIDER, actualCostUsd);
        }

        return {
          text,
          confidence: 0.78,
          latencyMs: Date.now() - startedAt,
          usage: { promptTokens, completionTokens },
          actualCostUsd,
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return {
          text: `${config.displayName} request failed (${message}). This response was not generated by a live model call; treat it as unverified.`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }
    },
  };
}
