import { afterEach, describe, expect, it, vi } from "vitest";
import type { AiPromptRequest } from "../types";
import { createOpenRouterProvider } from "./openRouterProvider";

const kimiConfig = {
  name: "kimi" as const,
  displayName: "Kimi K2 (Moonshot AI, via OpenRouter)",
  configured: true,
  mode: "remote" as const,
  status: "configured" as const,
  capabilities: ["general_chat" as const],
  languages: ["english"],
  costTier: "low" as const,
  latencyTier: "medium" as const,
};

const baseRequest: AiPromptRequest = {
  prompt: "Summarize this month's referral backlog.",
  context: { organizationId: "org-1", userId: "user-1", userRole: "Manager" },
};

const classification = {
  category: "general_chat" as const,
  sensitivity: "internal" as const,
  language: "english",
  requiredReasoning: "low" as const,
  requiresCitation: false,
  costPreference: "low" as const,
  latencyPreference: "balanced" as const,
  humanReviewRequired: false,
  confidence: 0.8,
  signals: [],
};

describe("createOpenRouterProvider", () => {
  afterEach(() => {
    vi.unstubAllGlobals();
    vi.unstubAllEnvs();
  });

  it("returns a low-confidence, clearly-labeled result without calling fetch when no API key is set", async () => {
    const fetchMock = vi.fn();
    vi.stubGlobal("fetch", fetchMock);
    const provider = createOpenRouterProvider(kimiConfig, {} as NodeJS.ProcessEnv);

    const result = await provider.complete(baseRequest, classification);

    expect(fetchMock).not.toHaveBeenCalled();
    expect(result.confidence).toBeLessThan(0.62);
    expect(result.text).toContain("not fully configured");
  });

  it("calls OpenRouter's chat completions endpoint and computes real cost from token usage", async () => {
    const fetchMock = vi.fn(async (url: string, init?: RequestInit) => {
      expect(url).toBe("https://openrouter.ai/api/v1/chat/completions");
      expect((init?.headers as Record<string, string>).Authorization).toBe("Bearer test-key");
      const body = JSON.parse(init?.body as string) as { model: string; messages: unknown[] };
      expect(body.model).toBe("moonshotai/kimi-k2");
      return new Response(JSON.stringify({
        choices: [{ message: { content: "Referral backlog is down 12% week over week." } }],
        usage: { prompt_tokens: 1000, completion_tokens: 500 },
      }), { status: 200 });
    });
    vi.stubGlobal("fetch", fetchMock);

    const provider = createOpenRouterProvider(kimiConfig, { OPENROUTER_API_KEY: "test-key" } as NodeJS.ProcessEnv);
    const result = await provider.complete(baseRequest, classification);

    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(result.text).toBe("Referral backlog is down 12% week over week.");
    expect(result.confidence).toBeGreaterThanOrEqual(0.62);
    expect(result.usage).toEqual({ promptTokens: 1000, completionTokens: 500 });
    // 1000 * 0.00000057 + 500 * 0.0000023 = 0.00057 + 0.00115 = 0.00172
    expect(result.actualCostUsd).toBeCloseTo(0.00172, 5);
  });

  it("returns a low-confidence, non-throwing result on a non-OK response", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response("rate limited", { status: 429 })));
    const provider = createOpenRouterProvider(kimiConfig, { OPENROUTER_API_KEY: "test-key" } as NodeJS.ProcessEnv);

    const result = await provider.complete(baseRequest, classification);

    expect(result.confidence).toBeLessThan(0.62);
    expect(result.text).toContain("429");
    expect(result.text).toContain("not generated by a live model call");
  });

  it("returns a low-confidence, non-throwing result when fetch itself throws", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => { throw new Error("network unreachable"); }));
    const provider = createOpenRouterProvider(kimiConfig, { OPENROUTER_API_KEY: "test-key" } as NodeJS.ProcessEnv);

    const result = await provider.complete(baseRequest, classification);

    expect(result.confidence).toBeLessThan(0.62);
    expect(result.text).toContain("network unreachable");
  });

  it("returns a low-confidence result when the response has no content", async () => {
    vi.stubGlobal("fetch", vi.fn(async () => new Response(JSON.stringify({ choices: [] }), { status: 200 })));
    const provider = createOpenRouterProvider(kimiConfig, { OPENROUTER_API_KEY: "test-key" } as NodeJS.ProcessEnv);

    const result = await provider.complete(baseRequest, classification);

    expect(result.confidence).toBeLessThan(0.62);
    expect(result.text).toContain("returned no content");
  });
});
