import type { AiProviderAdapter, AiProviderConfig, AiToolCall } from "../types";
import { checkProviderBudgetHeadroom, recordProviderSpend } from "../aiSpendGuard";

const OPENAI_ENDPOINT = "https://api.openai.com/v1/chat/completions";
const OPENAI_MODEL = "gpt-4o-mini";
const OPENAI_BUDGET_PROVIDER = "openai";

// Pricing verified against OpenAI's own published pricing at implementation time (2026-07-31),
// same "best known when written, may drift" honesty convention as openRouterProvider.ts.
const OPENAI_PRICING_PER_TOKEN = { prompt: 0.00000015, completion: 0.0000006 };

type OpenAiToolCall = {
  id?: string;
  function?: { name?: string; arguments?: string };
};

type OpenAiChatResponse = {
  choices?: Array<{ message?: { content?: string | null; tool_calls?: OpenAiToolCall[] } }>;
  usage?: { prompt_tokens?: number; completion_tokens?: number };
};

// Sprint 1 agentic chatbot (2026-08-16): defensive parse -- a model can emit malformed JSON in
// function.arguments; that must feed back into the loop as a tool-result error, never throw and
// crash the whole request.
function parseOpenAiToolCalls(raw: OpenAiToolCall[] | undefined): AiToolCall[] {
  if (!raw?.length) return [];
  return raw
    .filter((call): call is OpenAiToolCall & { id: string; function: { name: string } } =>
      Boolean(call.id && call.function?.name))
    .map((call) => {
      let args: Record<string, unknown> = {};
      try {
        args = call.function.arguments ? JSON.parse(call.function.arguments) : {};
      } catch {
        args = { __parseError: "OpenAI returned malformed JSON arguments for this tool call.", __raw: call.function.arguments };
      }
      return { id: call.id, name: call.function.name, arguments: args };
    });
}

export function createOpenAiProvider(
  config: AiProviderConfig,
  env: NodeJS.ProcessEnv = process.env,
): AiProviderAdapter {
  return {
    config,
    async complete(request) {
      const startedAt = Date.now();
      const apiKey = env.OPENAI_API_KEY;

      if (!apiKey) {
        return {
          text: `${config.displayName} is not fully configured (missing OpenAI API key). No live model call was made.`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }

      // Fail closed: real, billed calls to the founder's own OpenAI account only proceed once the
      // spend guard confirms real headroom below the account's safety margin. See aiSpendGuard.ts.
      const budget = await checkProviderBudgetHeadroom(OPENAI_BUDGET_PROVIDER);
      if (!budget.ok) {
        return {
          text: `${config.displayName} call skipped: ${budget.reason}`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }

      try {
        const response = await fetch(OPENAI_ENDPOINT, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${apiKey}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model: OPENAI_MODEL,
            messages: [
              { role: "user", content: request.prompt },
              ...(request.priorMessages ?? []).map((message) =>
                message.role === "assistant"
                  ? { role: "assistant", content: message.content, tool_calls: message.toolCalls?.map((call) => ({
                      id: call.id,
                      type: "function",
                      function: { name: call.name, arguments: JSON.stringify(call.arguments) },
                    })) }
                  : { role: "tool", tool_call_id: message.toolCallId, content: message.content },
              ),
            ],
            // Omitted entirely (not an empty array) when no tools are offered -- today's exact
            // request shape for every existing single-shot caller.
            ...(request.tools?.length ? {
              tools: request.tools.map((tool) => ({
                type: "function",
                function: { name: tool.name, description: tool.description, parameters: tool.parameters },
              })),
              tool_choice: "auto",
            } : {}),
          }),
        });

        if (!response.ok) {
          return {
            text: `${config.displayName} request failed (${response.status}). This response was not generated by a live model call; treat it as unverified.`,
            confidence: 0.3,
            latencyMs: Date.now() - startedAt,
          };
        }

        const payload = await response.json() as OpenAiChatResponse;
        const text = payload.choices?.[0]?.message?.content;
        // OpenAI legitimately returns content: null alongside tool_calls -- toolCalls, not text,
        // is what makes this response non-empty in that case.
        const toolCalls = parseOpenAiToolCalls(payload.choices?.[0]?.message?.tool_calls);
        const promptTokens = payload.usage?.prompt_tokens ?? 0;
        const completionTokens = payload.usage?.completion_tokens ?? 0;
        const actualCostUsd = Number((promptTokens * OPENAI_PRICING_PER_TOKEN.prompt + completionTokens * OPENAI_PRICING_PER_TOKEN.completion).toFixed(6));

        if (!text && toolCalls.length === 0) {
          return {
            text: `${config.displayName} returned no content. This response was not generated by a live model call; treat it as unverified.`,
            confidence: 0.3,
            latencyMs: Date.now() - startedAt,
          };
        }

        if (actualCostUsd > 0) {
          await recordProviderSpend(OPENAI_BUDGET_PROVIDER, actualCostUsd);
        }

        return {
          text: text ?? "",
          confidence: 0.78,
          latencyMs: Date.now() - startedAt,
          usage: { promptTokens, completionTokens },
          actualCostUsd,
          ...(toolCalls.length ? { toolCalls } : {}),
        };
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unknown error";
        return {
          text: `${config.displayName} request failed (${message}). This response was not generated by a live model call; treat it as unverified.`,
          confidence: 0.3,
          latencyMs: Date.now() - startedAt,
        };
      }
    },
  };
}
