#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';

const root = process.cwd();
const packageJsonPath = path.join(root, 'package.json');
const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
const version = packageJson.version || '0.0.0';
const buildNumber = process.env.MOBILE_BUILD_NUMBER || '1';
const commitSha = process.env.GITHUB_SHA || process.env.COMMIT_SHA || 'local';
const timestamp = new Date().toISOString();

const metadata = {
  version,
  buildNumber,
  commitSha,
  timestamp,
  note: 'Generated by scripts/mobile-version.mjs',
};

fs.mkdirSync(path.join(root, 'apps', 'mobile-capacitor', 'build-metadata'), { recursive: true });
fs.writeFileSync(path.join(root, 'apps', 'mobile-capacitor', 'build-metadata', 'build-metadata.json'), JSON.stringify(metadata, null, 2));
console.log(`[mobile] Version metadata written for ${version} build ${buildNumber} (${commitSha})`);
