export const demoStakeholderCards = [
  {
    name: "Dr. Purnima Bora",
    type: "Government",
    organization: "State Health Directorate",
    strength: "Strong",
    lastInteraction: "Mission Secretariat review, Jul 4",
    nextFollowUp: "Confirm oxygen maintenance owner by Jul 12",
    linkedProject: "Dibrugarh Oxygen Resilience Upgrade",
    linkedDocument: "Dibrugarh Oxygen Risk Register",
    suggestion: "Send a one-page executive note with maintenance variance and district SLA history.",
  },
  {
    name: "Director Lalthansangi",
    type: "Healthcare",
    organization: "Cachar District Hospital",
    strength: "Medium",
    lastInteraction: "Referral handoff call, Jul 3",
    nextFollowUp: "Share night transfer exception plan",
    linkedProject: "Cachar Maternal Referral Network",
    linkedDocument: "Maternal Referral Review Note",
    suggestion: "Request confirmation on ambulance escalation owner before the weekly review.",
  },
  {
    name: "Rupam Hazarika",
    type: "Partner",
    organization: "NEDFi Innovation Cell",
    strength: "Emerging",
    lastInteraction: "MSME workflow scoping, Jun 29",
    nextFollowUp: "Pilot data-sharing review",
    linkedProject: "MSME Credit Workflow Pilot",
    linkedDocument: "MSME Credit Triage SOP",
    suggestion: "Draft a pilot readiness email with credit workflow constraints and consent controls.",
  },
];
