import type { Document, DocumentActivity, DocumentCategory, DocumentTag, KnowledgeArticle } from "../../domain";

const now = "2026-07-04T00:00:00.000Z";

export const fallbackDocumentCategories: DocumentCategory[] = [
  {
    id: "cat_governance",
    organizationId: "org_public_safety",
    name: "Governance",
    slug: "governance",
    description: "Board, approval, and policy records.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cat_delivery",
    organizationId: "org_public_safety",
    name: "Delivery",
    slug: "delivery",
    description: "Program delivery and implementation documents.",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "cat_security",
    organizationId: "org_public_safety",
    name: "Security",
    slug: "security",
    description: "Risk, architecture, and compliance artifacts.",
    createdAt: now,
    updatedAt: now,
  },
];

export const fallbackDocumentTags: DocumentTag[] = [
  { id: "tag_risk", organizationId: "org_public_safety", name: "risk", color: "#8B1E2D", createdAt: now, updatedAt: now },
  { id: "tag_policy", organizationId: "org_public_safety", name: "policy", color: "#2C4A7C", createdAt: now, updatedAt: now },
  { id: "tag_pilot", organizationId: "org_public_safety", name: "pilot", color: "#1A6B4A", createdAt: now, updatedAt: now },
  { id: "tag_security", organizationId: "org_public_safety", name: "security", color: "#C9A227", createdAt: now, updatedAt: now },
];

export const fallbackDocuments: Document[] = [
  {
    id: "doc_architecture",
    organizationId: "org_public_safety",
    name: "Digital Identity Architecture Review.pdf",
    title: "Digital Identity Architecture Review",
    description: "Approved architecture packet for identity pilot governance.",
    storagePath: "organizations/org_public_safety/documents/doc_architecture/versions/v1/digital-identity-architecture-review.pdf",
    fileName: "digital-identity-architecture-review.pdf",
    fileSize: 2140000,
    mimeType: "application/pdf",
    documentType: "pdf",
    status: "active",
    visibility: "organization",
    categoryId: "cat_security",
    categoryName: "Security",
    ownerId: "user_raj_anand",
    currentVersion: 3,
    tags: ["security", "policy"],
    isFavorite: true,
    classification: "confidential",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "doc_pilot_plan",
    organizationId: "org_public_safety",
    name: "Pilot Readiness Checklist.md",
    title: "Pilot Readiness Checklist",
    description: "Markdown checklist used by program managers for pilot readiness.",
    storagePath: "organizations/org_public_safety/documents/doc_pilot_plan/versions/v1/pilot-readiness-checklist.md",
    fileName: "pilot-readiness-checklist.md",
    fileSize: 46000,
    mimeType: "text/markdown",
    documentType: "markdown",
    status: "active",
    visibility: "team",
    categoryId: "cat_delivery",
    categoryName: "Delivery",
    ownerId: "user_raj_anand",
    currentVersion: 1,
    tags: ["pilot"],
    classification: "internal",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "doc_archive",
    organizationId: "org_public_safety",
    name: "Legacy Vendor Risk Register.xlsx",
    title: "Legacy Vendor Risk Register",
    description: "Archived spreadsheet retained for audit and continuity.",
    storagePath: "organizations/org_public_safety/documents/doc_archive/versions/v1/legacy-vendor-risk-register.xlsx",
    fileName: "legacy-vendor-risk-register.xlsx",
    fileSize: 880000,
    mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    documentType: "xlsx",
    status: "archived",
    visibility: "shared",
    categoryId: "cat_governance",
    categoryName: "Governance",
    ownerId: "user_raj_anand",
    currentVersion: 2,
    tags: ["risk"],
    classification: "restricted",
    createdAt: now,
    updatedAt: now,
    archivedAt: now,
  },
];

export const fallbackKnowledgeArticles: KnowledgeArticle[] = [
  {
    id: "article_governance_model",
    organizationId: "org_public_safety",
    title: "Pilot Governance Model",
    bodyMarkdown: "Published operating model for pilot approvals, ownership, and escalation paths.",
    summary: "Defines how pilot approvals and escalations move across teams.",
    status: "published",
    categoryId: "cat_governance",
    categoryName: "Governance",
    authorUserId: "user_raj_anand",
    tags: ["policy", "pilot"],
    isFavorite: true,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "article_security_notes",
    organizationId: "org_public_safety",
    title: "Security Review Notes",
    bodyMarkdown: "Draft notes for the next security review cycle.",
    summary: "Draft notes for upcoming security review.",
    status: "draft",
    categoryId: "cat_security",
    categoryName: "Security",
    authorUserId: "user_raj_anand",
    tags: ["security"],
    createdAt: now,
    updatedAt: now,
  },
];

export const fallbackDocumentActivity: DocumentActivity[] = [
  {
    id: "activity_upload_architecture",
    organizationId: "org_public_safety",
    documentId: "doc_architecture",
    actorUserId: "user_raj_anand",
    action: "uploaded",
    metadata: { fileName: "digital-identity-architecture-review.pdf" },
    createdAt: now,
  },
  {
    id: "activity_archive_vendor",
    organizationId: "org_public_safety",
    documentId: "doc_archive",
    actorUserId: "user_raj_anand",
    action: "archived",
    metadata: { reason: "Superseded by Sprint 8 pilot register" },
    createdAt: now,
  },
];
